### ISSUE TITLE
WebGUI works but API not working

### ISSUE THREAD

**Issue by patrikwm** [AI-Riksarkivet/htrflow_app#4]
### What happened?

system: Ubuntu 22.04  i7-13700KF/64gb-ram/4080ti 

Web gui and Fast Track works as expected.

Running gradio_client against the run_htr_pipeline endpoint does not work.

### Steps To Reproduce

1. Install requirements.txt
2. Start server with `python3 app.py`
3. Start webserver `python3 -m http.server 8080`
4. run client 

### Client
```python
python app.py
Loaded as API: http://127.0.0.1:7860/ ✔
StatusUpdate(code=<Status.FINISHED: 'FINISHED'>, rank=0, queue_size=None, eta=None, success=False, time=datetime.datetime(2023, 11, 12, 17, 54, 50, 432654), progress_data=None)
Traceback (most recent call last):
  File "/home/patrik/projects/htrflow_client/.venv/lib/python3.10/site-packages/gradio_client/client.py", line 836, in _predict
    output = result["data"]
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/patrik/projects/htrflow_client/app.py", line 14, in <module>
    print(job.result())
  File "/home/patrik/projects/htrflow_client/.venv/lib/python3.10/site-packages/gradio_client/client.py", line 1131, in result
    return super().result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/patrik/projects/htrflow_client/.venv/lib/python3.10/site-packages/gradio_client/client.py", line 798, in _inner
    predictions = _predict(*data)
  File "/home/patrik/projects/htrflow_client/.venv/lib/python3.10/site-packages/gradio_client/client.py", line 842, in _predict
    if "error" in result and "429" in result["error"] and is_public_space:
TypeError: argument of type 'NoneType' is not iterable
```

### Server
```python
Traceback (most recent call last):
  File "/home/patrik/projects/htrflow_app/venv/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/patrik/projects/htrflow_app/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "/home/patrik/projects/htrflow_app/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/patrik/projects/htrflow_app/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/patrik/projects/htrflow_app/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/patrik/projects/htrflow_app/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/patrik/projects/htrflow_app/venv/lib/python3.10/site-packages/gradio/utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "/home/patrik/projects/htrflow_app/src/htr_pipeline/gradio_backend.py", line 92, in segment_to_xml_api
    rendered_xml = self.pipeline.running_htr_pipeline(image)
  File "/home/patrik/projects/htrflow_app/src/htr_pipeline/utils/helper.py", line 15, in wrap_func
    result = func(*args, **kwargs)
TypeError: Pipeline.running_htr_pipeline() missing 1 required positional argument: 'htr_tool_transcriber_model_dropdown'
```

**Comment by patrikwm** [comment]
`ba4de4ab538a654c932d4cd876d54850967d925e` was the last commit when i got the API to work. but there was other issues with that commit. like the models were not downloaded properly.

**Comment by Borg93** [comment]
Hi, I accepted your pull request 👍  and this some quick changes to make the api working now!

See this demo notebook here:
https://github.com/Swedish-National-Archives-AI-lab/htrflow_app/blob/main/notebooks/demo_api.ipynb

Currently their are only 3 models that are supported.

- Swedish from 16th-18th =  "Riksarkivet/satrn_htr"
- English text = "microsoft/trocr-base-handwritten"
- Latin and High German = "pstroe/bullinger-general-model"

In the future we will also add PyLaila model support and also a new model Swedish model for historical texts (It will be much better).
